language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors --use-wheel
- pip install coverage coveralls --use-wheel
script:
- coverage run --source=xml_factory setup.py test
after_success:
- coveralls
